# Generated by Django 5.2 on 2025-04-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
