# Generated by Django 5.2 on 2025-04-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('edit_task', 'Can edit task')]},
        ),
    ]
