# Generated by Django 5.2 on 2025-05-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
