# Generated by Django 5.1.7 on 2025-05-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='task_id',
        ),
    ]
